### ISSUE TITLE
Some Badge Embeds Missing.

### ISSUE THREAD

**Issue by TheMadog24** [lay295/TwitchDownloader#472]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Some badges that are used in the json/txt files are not being saved/embedded.
Most are, but some are not.

**Comment by ScrubN** [comment]
Badges are not embedded to .txt files. Also only first party twitch badges are embedded to the json download. If there are some first party badges that arent being embedded then an example json would be appreciated.

**Comment by TheMadog24** [comment]
My apologies, you are correct, just Json files.

> NOTE - This is a global badge, not a first party badge, like you said, so I assume this is not actually an issue, but I will provide my file anyway.


I have to provide the file with a third party, since I can't upload Json files here
https://file.io/eQ2jlRwOT5fA


I have formatted the json to make it easier.
Line 1169, `"_id": "bits",`,
and Line 1170, `"version": "800000"`

that embedded badge is not included in this file, as you can see on lines `866147`-`866154`
It is a global badge, as it can be found under the `https://badges.twitch.tv/v1/badges/global/display` directory
![image](https://user-images.githubusercontent.com/12008758/207761709-9b6006b9-69e1-4c97-828b-64d727e81ba4.png)

**Comment by TheMadog24** [comment]
Will Global badges be included in the Embed in the future?

**Comment by lay295** [comment]
Could you reupload the json file? Link isn't working. If it's small enough you can upload it here by changing the extension to txt

**Comment by ScrubN** [comment]
> Could you reupload the json file? Link isn't working. If it's small enough you can upload it here by changing the extension to txt

File.io only permits 1 download per file. I'm looking into it, we do fetch the global badge response

**Comment by TheMadog24** [comment]
File is over 61MBs, so too large for here, but here is another temporary link:
https://fastupload.io/en/W39sCarFEYJAiPK/file - Will be removed after 1 week

and here is a Google Drive link that I will remove after you have it downloaded.
https://drive.google.com/file/d/1MJdt5IChS0D9xahfpoKz2Sr5XEFLD21h/view?usp=sharing - Will be removed once you have it.

**Comment by ScrubN** [comment]
The problem is with how `JToken.Union()` works. The streamer has a `bits` object defined and so do the global badges, so Union() just takes the first object without comparing contents.

**Comment by TheMadog24** [comment]
I should note that this is just the file i was using for testing, and the only one I have atm, it was downloaded with the latest version.

**Comment by ScrubN** [comment]
After a few hours of troubleshooting I've learned that all badges are in fact embedded, though the 'bits' badges are embedded twice; first as the streamer specific and second as the global. Whatever tool you used to reformat the chat json removed the second occurrence.

[Here is your chat file before reformatting](https://drive.google.com/file/d/1CpdDL9kKqTtWzZiqn_-UqR9U1NoHR6mv/view?usp=share_link) (google drive)
If you open it in a standard editor like vscode, then do a search for `"name": "bits"`, you can see there are 2 occurrences. The first is the streamer-specific badges and the second is the global badges.

**Comment by TheMadog24** [comment]
I had to confirm this myself, so I re-downloaded the file again, and I now understand the issue.

The issue was not due to my Json Format Tool, what it was, is that I originally downloaded the file with v1.51.0
and then I used the "Chat Updater" Feature.

The new file I re-downloaded just now with v1.51.1 does indeed have all of the correct information now. Although, I am now not sure what the "Chat Updater" is meant to do.


In the file I uploaded and shared with you, there is only 1 occurrence of `"name":"bits"`, and that is just below `twitchBadges`,
however, in the new file I downloaded (before and after formatting) there are indeed 2 occurrences of `"name":"bits"`
once on line 866145, and again on line 866298.

I apologize for my error, and for having you look into this issue so much as a result.

**Comment by ScrubN** [comment]
> The issue was not due to my Json Format Tool, what it was, is that I originally downloaded the file with v1.51.0 and then I used the "Chat Updater" Feature.

So this issue does still apply, though I've found a quick and dirty fix. In doing so I also realized that chatupdate is a bit overcomplicated so I will be removing the `-R` argument

**Comment by TheMadog24** [comment]
I'm not exactly sure what the Chat Update function is supposed to do,
but from what I can tell, the issue stemmed from the 1.51.0 version, and was fixed in the 1.51.1 version.
My assumption was that the Chat Updater would fix the file of any issues, but not in this case.

if you need any more information from me, please let me know, I am Happy to help.
Especially since the project I am working on uses the Json files downloaded from your program.

**Comment by ScrubN** [comment]
> I'm not exactly sure what the Chat Update function is supposed to do, but from what I can tell, the issue stemmed from the 1.51.0 version, and was fixed in the 1.51.1 version.

The issue is with the `-R` argument of chatupdate and it is still present in 1.51.1. I'm merging `-R` and `-E` because they are nearly identical under the hood and the fact that they both existed caused a different bug whose solution ended up creating the bug this issue thread is about.

> My assumption was that the Chat Updater would fix the file of any issues, but not in this case.

In a perfect world it would, but finding every edge case isn't realistic and sometimes a full redownload is needed, although this edge case seems pretty important. I'll probably eventually find a solution to merge the streamer & global badges with serialization but for now this hotfix will have to do.

**Comment by TheMadog24** [comment]
> In a perfect world it would, but finding every edge case isn't realistic and sometimes a full redownload is needed, although this edge case seems pretty important. I'll probably eventually find a solution to merge the streamer & global badges with serialization but for now this hotfix will have to do.

Thank you very much for the fast Support, I do appreciate it.

**Comment by goldbattle** [comment]
See my discussion in https://github.com/lay295/TwitchDownloader/pull/474#issuecomment-1353725607 for the difference between the two modes (the help dialog should explain this).

If it is duplicating when updating the json, then that is definitely a bug. The updater should be able to take any old json and make it have the latest embeds in it that the newest version of the library supports.

**Comment by ScrubN** [comment]
When 1.51.2 comes out, the duplicates will be gone and chatupdate -R will be fixed.
